<h1>Editar empleado &quot;<?php echo $empleado->getNombre() ?>&quot;</h1>
<div>
    <?php $form->prepare(); ?>
    
    <?php echo $this->form()->openTag($form->setAttributes(['class' => 'form-horizontal'])); ?>
    
    
    <div class="form-group">
        <?php echo $this->formRow($form->get('dni')); ?>      
    </div>
    
    <div class="form-group">
        <?php echo $this->formRow($form->get('nombre')); ?>      
    </div>
    
    <div class="form-group">
        <?php echo $this->formRow($form->get('apellido')); ?>      
    </div>
    
    <div class="form-group">
        <?php echo $this->formSubmit($form->get('submit')->setAttributes(['class'  => 'btn btn-default'])); ?>      
    </div> 
   <?php echo $this->form()->closeTag(); ?>    
    
</div>