<h1>Nuevo empleado</h1>
<div>
    <?php $form->prepare(); ?>
    
    <?php echo $this->form()->openTag($form->setAttributes(['class' => 'form-horizontal'])); ?>
    
    
    <div class="form-group">
        <?php echo $this->formRow($form->get('dni')->setAttributes(['class'=>'form-control' ,'required'=>'required'])); ?>      
    </div>
    
    <div class="form-group">
        <?php echo $this->formRow($form->get('nombre')->setAttributes(['class'=>'form-control' ,'required'=>'required'])); ?>      
    </div>
    
    <div class="form-group">
        <?php echo $this->formRow($form->get('apellido')->setAttributes(['class'=>'form-control' ,'required'=>'required'])); ?>      
    </div>
    
    <div class="form-group">
        <?php echo $this->formSubmit($form->get('submit')->setAttributes(['class'  => 'btn btn-default'])); ?>      
    </div> 
   <?php echo $this->form()->closeTag(); ?>    
    
</div>